Added support for AVAudioRecorder and AVAudioPlayer APIs.
skiptools/skip-av pull request #1
Opened 2024-07-16 21:00 UTC by dashh5

2024-07-16 21:53 UTC, aabewhite requested changes
From what I've seen, the implementation looks great! One nitpick and one high-level change, though:

Nit: The file names don't need to be prefixed with "Skip". We generally match file names to the names of the types they contain.

High-level: I don't think you need the iOS code paths at all. I think you could put the entire content in #if SKIP blocks and just do the Android impl, basically. Because now that you're mirroring the AVFoundation API and devs can use this transparently, what we probably want them to do is something like this:

```
#if !SKIP 
import AVFoundation 
#else 
import SkipAV
#endif
```

That way the iOS app links directly against AVFoundation and doesn't risk SkipAV bugs and doesn't need to use or link Skip libs. Given that our transpiler lets you just `import AVKit` and maps it to `import skip.av` in the Kotlin automatically, we'll probably do the same for AVFoundation in the future too.

Does that make sense?

We'll also want to update the README.md with a supported API listing like we have in SkipLib, SkipFoundation, SkipUI, etc. But you've done enough - we can handle that part!

2024-07-16 22:51 UTC, dashh5 commented
Updated to only include Android implementation, added to the Readme, and renamed the relevant files. Thanks for the the suggestions!

2024-07-17 02:43 UTC, aabewhite requested changes
Almost done...

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +import SwiftUI
Do we need this import? Seems like you can remove it and just have one #if SKIP around the whole source

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +    weak open var delegate: AVAudioPlayerDelegate?
It looks to me like we never actually make any calls on the delegate. So we should mark this @available(*, unavailable) so people get errors if they try to use it in Android

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +    private var _pan: Double = 0.0
_pan isn't used AFAICT

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +    /// NOTE: newValue's Kotlin Float type is confusing the transpiler. Leaving these two properties to be fixed in a future PR.
What was the issue here? If the Swift API is for Double but the Kotlin mediaPlayer expects Float, you can just pass Float(doubleValue). But sounds like maybe it was something else?

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioRecorder.swift
> +import SwiftUI
Same: I don't think we need to import SwiftUI, do we?

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioRecorder.swift
> +            FileOutputStream(file, false).close()
What does this do? Maybe deserves a comment.

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioRecorder.swift
> +        return TimeInterval(recorder?.maxAmplitude ?? 0) / 32767.0
Why is this the same as peakPower?

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVAudioRecorder.swift
> +    public var isMeteringEnabled: Bool {
We don't seem to do anything with this value. Should it be marked @available(*, unavailable)?

(Also doesn't seem to be any reason to having a backing private var rather than just making this a stored property)

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/AVConstants.swift
> +import Foundation
Can #if SKIP around this whole file too

2024-07-17 02:43 UTC, aabewhite commented on Sources/SkipAV/CoreAudio.swift
> +import Foundation
Can #if SKIP around this whole file too

2024-07-17 17:00 UTC, dashh5 commented
Added the delegate calls for AVAudioRecorder and AVAudioPlayer, #if SKIP'd the whole files, and cleaned the methods.

2024-07-17 17:12 UTC, aabewhite reviewed
A few very small changes, and we'll merge!

2024-07-17 17:12 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +        mediaPlayer?.setOnCompletionListener { [weak self] _ in
Fine to keep here in case we update the transpiler, but note that right now Skip ignores all the weak stuff and relies on Java GC

2024-07-17 17:12 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +    /// NOTE: newValue's Kotlin Float type is confusing the transpiler. Leaving these two properties to be fixed in a future PR.
Is this comment still relevant?

2024-07-17 17:12 UTC, aabewhite commented on Sources/SkipAV/AVAudioPlayer.swift
> +    private func clamp<T: Comparable>(_ value: T, min: T, max: T) -> T {
Is this function used?

2024-07-17 17:12 UTC, aabewhite commented on Sources/SkipAV/AVAudioRecorder.swift
> +    var meteringEnabled = false
public?

2024-07-17 17:18 UTC, aabewhite approved these changes

2024-07-17 17:19 UTC, merged